### ISSUE TITLE
GenICam exception thrown: NULL pointer dereferenced

### ISSUE THREAD

**Issue by twbabyduck** [roncapat/ROS2-HAL-LucidLabs-Helios2#1]
Dear Patrick,

Could you take a look and see what might be the reason that Helios2 cannot launch successfully?
Thanks for your help :) 

**Environment:**

ROS2 Eloquent/Foxy
Ubuntu 18.04/20.04
Model: Helios2
Firmware version: 1.5.24.2/1.8.0.0
Arena SDK version: v0.1.59.0

**Console Log:**
```
[INFO] [1647835073.441264519] [hal_lucidlabs_helios2]: Model name: HLT003S-001
[INFO] [1647835074.002205744] [hal_lucidlabs_helios2]: Exposure setting: Exp62_5Us
[ERROR] [1647835074.002427586] [hal_lucidlabs_helios2]: GenICam exception thrown: NULL pointer dereferenced : LogicalErrorException thrown (file 'Pointer.h', line 105)
```

**Comment by roncapat** [comment]
In CMakeLists.txt:
- comment line 16
- uncomment line 17

Run Colcon again.
When the node crashes, an extra line shall appear on your terminal (something saying that the node exited with status XXX)... Report here the full string so that I can give you next debugging steps to help me trace better the problem.

**Comment by twbabyduck** [comment]
> Moreover:
> 
>     * run `sudo apt install aravis-tools`
> 
>     * run `arv-tool-0.6 features`
> 
>     * paste all the output here (as an attachment if its too big)

The attachment is arv-tool output log file.

[arv-tool.log](https://github.com/roncapat/ROS2-HAL-LucidLabs-Helios2/files/8331023/arv-tool.log)

**Comment by twbabyduck** [comment]
> In CMakeLists.txt:
> 
>     * comment line 16
> 
>     * uncomment line 17
> 
> 
> Run Colcon again. When the node crashes, an extra line shall appear on your terminal (something saying that the node exited with status XXX)... Report here the full string so that I can give you next debugging steps to help me trace better the problem.

Since the output from console is exactly the same, so I tried to execute the gdb directly with command `ros2 run --prefix 'gdb -ex run --args' hal_lucidlabs_helios2 HALHelios` 


The output is shown in this attachment

[gdb-lucid.log](https://github.com/roncapat/ROS2-HAL-LucidLabs-Helios2/files/8331054/gdb-lucid.log)

**Comment by roncapat** [comment]
It seems to me that you do not reach line 152 of the code for a bad acquisition mode setting. Which is the value associated in config.yaml or launch file for "mode"? Could you paste the full configuration for the node?

**Comment by roncapat** [comment]
Also, note that for your Helios model:
```
 "HighSpeedDistance2500mmSingleFreq",
 "HighSpeedDistance1250mmSingleFreq",
 "HighSpeedDistance625mmSingleFreq",
```
modes are not available.

**Comment by twbabyduck** [comment]
> It seems to me that you do not reach line 152 of the code for a bad acquisition mode setting. Which is the value associated in config.yaml or launch file for "mode"? Could you paste the full configuration for the node?

Here is the params.yaml file that I used:

```
hal_lucidlabs_helios2:
  ros__parameters:
    output_topic: "/point_cloud"
    threshold: 200
    spatial_filter: true
    flying_filter: true
    accumulate_frames: 1
    frame_id: "camera"
    # Options dumped with arv-tool
      #Enumeration: 'ExposureTimeSelector'
        #EnumEntry: (0) 'Exp62_5Us'
        #EnumEntry: (1) 'Exp250Us'
        #EnumEntry: (2) 'Exp1000Us'
    exposure_level: 0
    # Options dumped with arv-tool
      #Enumeration: 'Scan3dOperatingMode'
        #EnumEntry: (0) 'HighSpeedDistance2500mmSingleFreq'
        #EnumEntry: (1) 'HighSpeedDistance1250mmSingleFreq'
        #EnumEntry: (2) 'HighSpeedDistance625mmSingleFreq'
        #EnumEntry: (3) 'Distance8300mmMultiFreq'
        #EnumEntry: (4) 'Distance6000mmSingleFreq'
        #EnumEntry: (5) 'Distance5000mmMultiFreq'
        #EnumEntry: (6) 'Distance4000mmSingleFreq'
        #EnumEntry: (7) 'Distance3000mmSingleFreq'
        #EnumEntry: (8) 'Distance1250mmSingleFreq'
    mode: 5
```
